version: '3.8'

services:
  # 1. Redis
  redis:
    image: redis:7-alpine
    container_name: ai-gateway-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - gateway-net

  # 2. Mock Backend
  mock-backend:
    build: ./mock-backend       # Points to the folder containing main.py and Dockerfile
    container_name: ai-gateway-mock
    ports:
      - "5001:5001"             # Maps localhost:5001 to container:5001
    environment:
      - SERVICE_NAME=Mock-GPT-4
    networks:
      - gateway-net
    restart: always

volumes:
  redis_data:

networks:
  gateway-net: